demo/config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  get "posts/:slug", to: "posts#show", as: :post
  get "categories", to: "categories#index", as: :categories
  get "categories/:slug", to: "categories#show", as: :category
  get ":slug", to: "pages#show", as: :page

  namespace :admin do
    resources :posts
    resources :pages
    resources :categories
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

demo/app/models/admin.rb
module Admin
  def self.table_name_prefix
    "admin_"
  end
end

demo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

demo/app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :posts

  def to_param
    slug
  end
end

demo/app/models/page.rb
class Page < ApplicationRecord
  def to_param
    slug
  end
end

demo/app/models/post.rb
class Post < ApplicationRecord
  has_and_belongs_to_many :categories

  scope :published, -> { where(published: true).order(published_at: :desc) }

  def to_param
    slug
  end
end

demo/app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /admin/categories
  def index
    @categories = Category.all
  end

  # GET /admin/categories/1
  def show
  end

  # GET /admin/categories/new
  def new
    @category = Category.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to [:admin, @category], notice: "Category was successfully created."
    else
      render :new, status: :unprocessable_content
    end
  end

  # PATCH/PUT /admin/categories/1
  def update
    if @category.update(category_params)
      redirect_to [:admin, @category], notice: "Category was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_content
    end
  end

  # DELETE /admin/categories/1
  def destroy
    @category.destroy!
    redirect_to admin_categories_path, notice: "Category was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [ :name, :slug ])
    end
end

demo/app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]

  # GET /admin/pages
  def index
    @pages = Page.all
  end

  # GET /admin/pages/1
  def show
  end

  # GET /admin/pages/new
  def new
    @page = Page.new
  end

  # GET /admin/pages/1/edit
  def edit
  end

  # POST /admin/pages
  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to [:admin, @page], notice: "Page was successfully created."
    else
      render :new, status: :unprocessable_content
    end
  end

  # PATCH/PUT /admin/pages/1
  def update
    if @page.update(page_params)
      redirect_to [:admin, @page], notice: "Page was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_content
    end
  end

  # DELETE /admin/pages/1
  def destroy
    @page.destroy!
    redirect_to admin_pages_path, notice: "Page was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.expect(page: [ :title, :slug, :body ])
    end
end

demo/app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /admin/posts
  def index
    @posts = Post.all
  end

  # GET /admin/posts/1
  def show
  end

  # GET /admin/posts/new
  def new
    @post = Post.new
  end

  # GET /admin/posts/1/edit
  def edit
  end

  # POST /admin/posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to [:admin, @post], notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_content
    end
  end

  # PATCH/PUT /admin/posts/1
  def update
    if @post.update(post_params)
      redirect_to [:admin, @post], notice: "Post was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_content
    end
  end

  # DELETE /admin/posts/1
  def destroy
    @post.destroy!
    redirect_to admin_posts_path, notice: "Post was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.expect(post: [ :title, :slug, :body, :published_at, :published ])
    end
end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

demo/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by!(slug: params[:slug])
    @posts = @category.posts.published
  end
end

demo/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find_by!(slug: params[:slug])
  end
end

demo/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.published
  end

  def show
    @post = Post.published.find_by!(slug: params[:slug])
  end
end

demo/app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

demo/app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

demo/app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/views/admin/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <div>
    <strong>Name:</strong>
    <%= category.name %>
  </div>

  <div>
    <strong>Slug:</strong>
    <%= category.slug %>
  </div>

</div>

demo/app/views/admin/categories/_form.html.erb
<%= form_with(model: [:admin, category]) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :slug, style: "display: block" %>
    <%= form.text_field :slug %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

demo/app/views/admin/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", [:admin, @category] %> |
  <%= link_to "Back to categories", admin_categories_path %>
</div>

demo/app/views/admin/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Categories" %>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", [:admin, category] %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_admin_category_path %>

demo/app/views/admin/categories/new.html.erb
<% content_for :title, "New category" %>

<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", admin_categories_path %>
</div>

demo/app/views/admin/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_admin_category_path(@category) %> |
  <%= link_to "Back to categories", admin_categories_path %>

  <%= button_to "Destroy this category", [:admin, @category], method: :delete %>
</div>

demo/app/views/admin/pages/_form.html.erb
<%= form_with(model: [:admin, page]) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :slug, style: "display: block" %>
    <%= form.text_field :slug %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.textarea :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

demo/app/views/admin/pages/_page.html.erb
<div id="<%= dom_id page %>">
  <div>
    <strong>Title:</strong>
    <%= page.title %>
  </div>

  <div>
    <strong>Slug:</strong>
    <%= page.slug %>
  </div>

  <div>
    <strong>Body:</strong>
    <%= page.body %>
  </div>

</div>

demo/app/views/admin/pages/edit.html.erb
<% content_for :title, "Editing page" %>

<h1>Editing page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Show this page", [:admin, @page] %> |
  <%= link_to "Back to pages", admin_pages_path %>
</div>

demo/app/views/admin/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Pages" %>

<h1>Pages</h1>

<div id="pages">
  <% @pages.each do |page| %>
    <%= render page %>
    <p>
      <%= link_to "Show this page", [:admin, page] %>
    </p>
  <% end %>
</div>

<%= link_to "New page", new_admin_page_path %>

demo/app/views/admin/pages/new.html.erb
<% content_for :title, "New page" %>

<h1>New page</h1>

<%= render "form", page: @page %>

<br>

<div>
  <%= link_to "Back to pages", admin_pages_path %>
</div>

demo/app/views/admin/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @page %>

<div>
  <%= link_to "Edit this page", edit_admin_page_path(@page) %> |
  <%= link_to "Back to pages", admin_pages_path %>

  <%= button_to "Destroy this page", [:admin, @page], method: :delete %>
</div>

demo/app/views/admin/posts/_form.html.erb
<%= form_with(model: [:admin, post]) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :slug, style: "display: block" %>
    <%= form.text_field :slug %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.textarea :body %>
  </div>

  <div>
    <%= form.label :published_at, style: "display: block" %>
    <%= form.datetime_field :published_at %>
  </div>

  <div>
    <%= form.label :published, style: "display: block" %>
    <%= form.checkbox :published %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

demo/app/views/admin/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <div>
    <strong>Title:</strong>
    <%= post.title %>
  </div>

  <div>
    <strong>Slug:</strong>
    <%= post.slug %>
  </div>

  <div>
    <strong>Body:</strong>
    <%= post.body %>
  </div>

  <div>
    <strong>Published at:</strong>
    <%= post.published_at %>
  </div>

  <div>
    <strong>Published:</strong>
    <%= post.published %>
  </div>

</div>

demo/app/views/admin/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", [:admin, @post] %> |
  <%= link_to "Back to posts", admin_posts_path %>
</div>

demo/app/views/admin/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", [:admin, post] %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_admin_post_path %>

demo/app/views/admin/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", admin_posts_path %>
</div>

demo/app/views/admin/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_admin_post_path(@post) %> |
  <%= link_to "Back to posts", admin_posts_path %>

  <%= button_to "Destroy this post", [:admin, @post], method: :delete %>
</div>

demo/app/views/categories/index.html.erb
<h1>Categories</h1>

<ul>
  <% @categories.each do |category| %>
    <li>
      <%= link_to category.name, category_path(category) %>
      (<%= category.posts.published.count %>)
    </li>
  <% end %>
</ul>

demo/app/views/categories/show.html.erb
<h1>Category: <%= @category.name %></h1>

<div class="post-list">
  <% @posts.each do |post| %>
    <article>
      <h2><%= link_to post.title, post_path(post) %></h2>
      <p class="post-meta"><%= post.published_at.strftime("%B %d, %Y") %></p>
      <p><%= truncate(post.body, length: 200) %></p>
    </article>
  <% end %>
</div>

<p><%= link_to "&larr; All categories".html_safe, categories_path %></p>

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "My Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag :app %>
    <%= javascript_importmap_tags %>
    <style>
      body { font-family: system-ui, -apple-system, sans-serif; max-width: 800px; margin: 0 auto; padding: 1rem; color: #333; }
      nav { border-bottom: 2px solid #eee; padding-bottom: 1rem; margin-bottom: 2rem; display: flex; align-items: center; }
      nav a { margin-right: 1.5rem; text-decoration: none; color: #0066cc; font-weight: 500; }
      nav .github { margin-left: auto; margin-right: 0; }
      nav a:hover { text-decoration: underline; }
      .post-meta { color: #666; font-size: 0.9rem; margin-bottom: 0.5rem; }
      .post-list article { margin-bottom: 2rem; padding-bottom: 1.5rem; border-bottom: 1px solid #eee; }
      .post-list article:last-child { border-bottom: none; }
      .category-tag { display: inline-block; background: #e8f0fe; color: #1a73e8; padding: 0.2rem 0.6rem; border-radius: 3px; font-size: 0.85rem; text-decoration: none; margin-right: 0.5rem; }
      .category-tag:hover { background: #d2e3fc; }
      code { background: #f4f4f4; padding: 0.15rem 0.4rem; border-radius: 3px; font-size: 0.9em; }
      pre { background: #f4f4f4; padding: 1rem; border-radius: 4px; overflow-x: auto; }
      pre code { background: none; padding: 0; }
      footer { margin-top: 3rem; padding-top: 1rem; border-top: 2px solid #eee; color: #999; font-size: 0.85rem; }
    </style>
  </head>

  <body>
    <nav>
      <%= link_to "Home", root_path %>
      <%= link_to "About", page_path("about") %>
      <%= link_to "Categories", categories_path %>
      <%= link_to "GitHub", "https://github.com/ianterrell/rails2static", class: "github" %>
    </nav>

    <%= yield %>

    <footer>
      <p>Built with Rails &amp; rails2static</p>
    </footer>
  </body>
</html>

demo/app/views/pages/show.html.erb
<h1><%= @page.title %></h1>

<%= sanitize simple_format(@page.body), tags: %w[p br code pre] %>

demo/app/views/posts/index.html.erb
<h1>Blog</h1>

<div class="post-list">
  <% @posts.each do |post| %>
    <article>
      <h2><%= link_to post.title, post_path(post) %></h2>
      <p class="post-meta">
        <%= post.published_at.strftime("%B %d, %Y") %>
        <% post.categories.each do |cat| %>
          <%= link_to cat.name, category_path(cat), class: "category-tag" %>
        <% end %>
      </p>
      <p><%= truncate(post.body, length: 200) %></p>
    </article>
  <% end %>
</div>

demo/app/views/posts/show.html.erb
<article>
  <h1><%= @post.title %></h1>
  <p class="post-meta">
    <%= @post.published_at.strftime("%B %d, %Y") %>
    <% @post.categories.each do |cat| %>
      <%= link_to cat.name, category_path(cat), class: "category-tag" %>
    <% end %>
  </p>

  <%= sanitize simple_format(@post.body), tags: %w[p br code pre] %>
</article>

<p><%= link_to "&larr; Back to all posts".html_safe, root_path %></p>